# Generated by Django 3.2.9 on 2023-04-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuedj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(max_length=500, upload_to='vuedj/static/images/'),
        ),
    ]
