# Generated by Django 3.2.9 on 2023-04-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuedj', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(max_length=500, upload_to='vuedj/vue_inte/public/img'),
        ),
    ]
